services:
  recipebook-db:
    image: pgvector/pgvector:pg18
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: RecipeAdmin
      POSTGRES_PASSWORD: R3c1peB00k
      POSTGRES_DB: recipebook
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./db/CreateDB.sql:/docker-entrypoint-initdb.d/CreateDB.sql

  recipebook-server:
    build:
      context: ./server
    container_name: recipebook-server
    environment:
      DATABASE_URL: postgresql://postgres:postgres@recipebook-db:5432/recipebook
    depends_on:
      - recipebook-db
    ports:
      - "8000:8000"

  recipebook-web:
    build:
      context: ./web
    container_name: recipebook-web
    depends_on:
      - recipebook-server
    ports:
      - "8650:80"
    restart: unless-stopped

volumes:
  db_data: