services:

  recipebook-web:
    build:
      context: ./web
    container_name: recipebook-web
    environment:
      BACKEND_URL: http://recipebook-server:8000 # No trailing slash to preserve /api/ calls
      S3_URL: http://recipebook-rustfs:9000/ # with trailing slash to strip /s3/ prefix
    # depends_on:
    # - recipebook-server
    ports:
      - "8650:80"
    restart: unless-stopped

  recipebook-server:
    build:
      context: ./server
    container_name: recipebook-server
    environment:
      DATABASE_URL: postgresql://${PG_USER}:${PG_PASSWORD}@recipebook-db:5432/recipebook
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      LLM_MODEL: ${LLM_MODEL}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL}
      EMBEDDING_VECTOR_SIZE: ${EMBEDDING_VECTOR_SIZE}
      LOG_LEVEL: ${LOG_LEVEL}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_PUBLIC_ENDPOINT: ${S3_PUBLIC_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET} # <- not required, backend can use a default name
      S3_KEY: ${S3_KEY:?Env variable S3_KEY is required}
      S3_SECRET: ${S3_SECRET:?Env variable S3_SECRET is required}
    depends_on:
      - recipebook-db
      - recipebook-rustfs
      - recipebook-ollama  # Enable or disable this if you want to use the Ollama container
    ports:
      - "8000:8000"

  recipebook-db:
    image: pgvector/pgvector:pg18
    container_name: recipebook-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER:?Env variable PG_USER is required}
      POSTGRES_PASSWORD: ${PG_PASSWORD:?Env variable PG_PASSWORD is required}
      POSTGRES_DB: recipebook
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./db/CreateDB.sql:/docker-entrypoint-initdb.d/CreateDB.sql

  recipebook-rustfs:
    image: rustfs/rustfs:latest
    container_name: recipebook-rustfs
    ports:
      - "9000:9000" # S3 API port
      - "9001:9001" # Console port
    environment:
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001
      RUSTFS_CONSOLE_ENABLE: true
      RUSTFS_CORS_ALLOWED_ORIGINS: "*"
      RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: "*"
      RUSTFS_ACCESS_KEY: ${S3_KEY:?Env variable S3_KEY is required}
      RUSTFS_SECRET_KEY: ${S3_SECRET:?Env variable S3_SECRET is required}
    volumes:
      - rustfs_data:/data
      - rustfs_logs:/app/logs
    restart: unless-stopped

  recipebook-ollama:
      image: ollama/ollama:latest
      container_name: recipebook-ollama
      restart: unless-stopped
      ports:
        - "${OLLAMA_PORT}:11434"
      volumes:
        - ollama_data:/root/.ollama

volumes:
  db_data:
  rustfs_data:
  rustfs_logs:
  ollama_data:
