name: Build and deploy Docker image stack on self-hosted runner

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and restart
        run: |
          EC=/home/gh-runner/.secrets/recipebook.env

          # sanity check
          if [ ! -r "$EC" ]; then
            echo "Missing env file: $EC" >&2
            exit 1
          fi

          # Test the config (don't print output because .env contains secrets)
          docker compose --env-file "$EC" config > /dev/null

          docker compose --env-file "$EC" down
          docker compose --env-file "$EC" pull
          docker compose --env-file "$EC" up -d --build
          docker image prune -f
